### ISSUE TITLE
Session API outdated

### ISSUE THREAD

**Issue by magegu** [figo-connect/ruby-figo#20]
Hi guys,

I just installed the latest 1.3.2 gem via bundler into my rails app. i'm using 4.2.7 on ruby 2.3.1.
Unfortunately, it seems that the underlying HTTP API changed and the Session constructor is not working anymore.  At least the first demo call from your docs is not working at the moment.

this is my `rails console` output:

```
2.3.1 :001 > session = Figo::Session.new("ASHWLIkouP2O6_bgA2wWReRhletgWKHYjLqDaqb0LFfamim9RjexTo22ujRIP_cjLiRiSyQXyt2kM1eXU2XLFZQ0Hro15HikJQT_eNeT_9XQ")
ArgumentError: wrong number of arguments (given 2, expected 0)
	from /Users/magegu/.rvm/gems/ruby-2.3.1/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:505:in `initialize'
	from /Users/magegu/.rvm/gems/ruby-2.3.1/gems/figo-1.3.2/lib/helpers/https.rb:9:in `initialize'
	from /Users/magegu/.rvm/gems/ruby-2.3.1/gems/figo-1.3.2/lib/figo.rb:123:in `new'
	from /Users/magegu/.rvm/gems/ruby-2.3.1/gems/figo-1.3.2/lib/figo.rb:123:in `initialize'
	from (irb):1:in `new'
```

**Comment by dzdidi** [comment]
It was fixed here: https://github.com/figo-connect/ruby-figo/issues/19
I've just updated gem (v1.3.3)

**Comment by magegu** [comment]
merci!
