### ISSUE TITLE
create_user is not accepting 'send_newsletter' parameter

### ISSUE THREAD

**Issue by mduqueoviedo** [figo-connect/ruby-figo#4]
When I try to create a user with the create_user function I get the following error:
Figo::Error (Invalid parameter send_newsletter)

I dug a bit and tried a local version of the entire library, so after adding some logging I can show this:

**Data hash**
> {"name"=>"Test testing", "email"=>"test@test.com", "password"=>"demo1234", "language"=>"en", "send_newsletter"=>true, "affiliate_client_id"=>"[HIDDEN]"}

**Encoded URL**
> name=Test+testing&email=test%40test.com&password=demo1234&language=en&send_newsletter=true&affiliate_client_id=[HIDDEN]

**Response**
> Completed 500 Internal Server Error in 5254ms

> Figo::Error (Invalid parameter send_newsletter):
>  lib/figo.rb:88:in `request'
>  lib/figo.rb:140:in `query_api'
>  lib/figo.rb:211:in `create_user'
>  app/controllers/operations_controller.rb:18:in `create_user'

As far as I understand, the backend of the API is not accepting send_newsletter parameter. I have tried to modify the source, let it by default, use "True", "true", "False", 0... None of them is accepted. 
It only works if I don't send the parameter at all:
    `data = { 'name' => name, 'email' => email, 'password' => password, 'language' => language, 'affiliate_client_id' => @client_id}`

I will submit a pull request so you can see the problem.

**Comment by javaes** [comment]
Thanks for your fix. send_newsletter is not implemented yet.
